<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.learning</groupId>
	<artifactId>e-learning-microservices</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>E-Learning Microservices</name>
	<description>Aggregator for E-Learning Microservices</description>

	<modules>
		<module>ServiceRegistry</module>
		<module>ContentService</module>
		<module>Courseservice</module>
		<module>userservice</module>
		<module>UnitService</module>
	</modules>
</project>
